name: Build and Push Docker Image

on: # zizmor: ignore[cache-poisoning]
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu-22-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ubuntu-22.04
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/pyvista/arc-runners:ubuntu22.04-${{ github.sha }}
            ghcr.io/pyvista/arc-runners:ubuntu22.04-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke test runner container
        run: |
          docker run -d --name test-runner ghcr.io/pyvista/arc-runners:ubuntu22.04-${{ github.sha }}
          sleep 10
          docker logs test-runner | tee logs.txt
          docker ps -f name=test-runner --format '{{.Status}}' | grep -q 'Up'
          docker stop test-runner

  build-ubuntu-24-04-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ubuntu-24.04-gpu
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/pyvista/arc-runners:ubuntu24.04-gpu-${{ github.sha }}
            ghcr.io/pyvista/arc-runners:ubuntu24.04-gpu-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Smoke test runner container
        run: |
          docker run -d --name test-runner ghcr.io/pyvista/arc-runners:ubuntu24.04-gpu-${{ github.sha }}
          sleep 10
          docker logs test-runner | tee logs.txt
          docker ps -f name=test-runner --format '{{.Status}}' | grep -q 'Up'
          docker stop test-runner